### ISSUE TITLE
Sprint 2 finalize

### ISSUE THREAD

**Issue by afy** [mebakid74/D0018E-Databasteknik-2023#12]
For demo:
-Serverside credentials
-Backend route fixes
-Working cart UI (tex, increment button)
-Finalize frontend UI
-Add review db interactions

Misc:
-Report: Cart system, Review system, Final read through

**Comment by mebakid74** [comment]
Create an account and login not working as expected. !userValid ? might be the problem

**Comment by Nearyn-hub** [comment]
Issue loading account or basket.

**Comment by mebakid74** [comment]
Sprint 2 finalization done!
