### ISSUE TITLE
MySQL database fixes.

### ISSUE THREAD

**Issue by afy** [mebakid74/D0018E-Databasteknik-2023#5]
(FIXED) Found so far:
-parent category should be able to be null
-automatic id assignment; either incrementing counter or something like SELECT AS_BASE64(RANDOM_BYTES(#length))

**Comment by afy** [comment]
(FIXED) New list:
-Stray foreign key reference in reciept to old table.

**Comment by Nearyn-hub** [comment]
Shopping basket:
- Make an order cap of max. 10 products per item buyable, if 11 selected raise Error and message "contact costumer service"

**Comment by afy** [comment]
(FIXED)
-Redundant "productscol" in products table added by mistake 
-Rewrite queries to use atomic units

**Comment by afy** [comment]
Add imagepath attribute to collections
